name: Run Cypress Tests

on: 
  push:
    branches:
      - feat/create-tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    continue-on-error: true  # Continua mesmo que os testes falhem
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Cypress Tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          npx cypress run --record --parallel --ci-build-id=github-${{ github.run_id }} --group container-${{ matrix.container }}
